# Generated by Django 3.1.7 on 2021-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('shopid', models.IntegerField()),
                ('pickuprequired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposalid', models.IntegerField()),
                ('agentid', models.IntegerField()),
                ('pickupdate', models.DateField()),
                ('confirmation', models.BooleanField(default=False)),
                ('charges', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('rewards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='scrapshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('stockloaded', models.IntegerField()),
                ('image', models.ImageField(upload_to='pics/')),
                ('gmaplink', models.CharField(max_length=150)),
                ('shopmobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='shoppayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.IntegerField()),
                ('collectedqty', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('daterecieved', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='wasteprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=30)),
                ('priceperkg', models.IntegerField()),
            ],
        ),
    ]
