# Generated by Django 3.1.7 on 2021-04-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plasticWM', '0004_auto_20210424_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='locality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='plasticWM.locality'),
            preserve_default=False,
        ),
    ]
