# Generated by Django 3.1.7 on 2021-04-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasticWM', '0005_extendeduser_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='disposaldone',
            field=models.BooleanField(default=False),
        ),
    ]
